### ISSUE TITLE
Open source license

### ISSUE THREAD

**Issue by elpdspec** [heroku/ranch_proxy_protocol#19]
Hi,
Would you consider to change the license to some kind of standard open source license ?

**Comment by ferd** [comment]
We use the BSD license already?

**Comment by elpdspec** [comment]
Thank you for the quick reply. 
I understand. My mistake. Due to some bureaucratic issues it would be preferable if the license did not require license and copyright notice to be put. Like http://choosealicense.com/licenses/unlicense. 
I understand it is not something minor so I am just asking.

**Comment by ferd** [comment]
I do believe the copyright notices will remain in the LICENSE file we have, from the point of view that unlicense may on the other hand cause legal issues in open source components on our end.

**Comment by elpdspec** [comment]
I understand. 
Thank you for your prompt response.
