### ISSUE TITLE
ranch_proxy_ssl does not support `eccs` transport option

### ISSUE THREAD

**Issue by tomciopp** [heroku/ranch_proxy_protocol#32]
Environment info:
OS: Mac OSX 10.13.2 / Alpine Linux 3.7
erlang: 20.2.2
elixir: 1.5.2
ranch_proxy_protocol: 1.4.2

I'm attempting to use ranch_proxy_protocol but I'm running into errors when I pass my previous transport options to ranch_proxy_ssl. (I'm calling from elixir so syntax may be a bit different)

    trans_opts = [
      port: 443,
      cert: cert,
      cacerts: cacerts,
      key: key,
      versions: [:'tlsv1.2', :'tlsv1.1'],
      protocol_options: [
        compress: true
      ],
      ciphers: [
        'ECDHE-ECDSA-AES256-GCM-SHA384',
        'ECDHE-ECDSA-AES256-SHA384',
        'ECDHE-ECDSA-AES128-GCM-SHA256',
        'ECDHE-ECDSA-AES128-SHA256',
        'ECDHE-ECDSA-AES256-SHA',
        'ECDHE-ECDSA-AES128-SHA',
        'ECDHE-RSA-AES256-GCM-SHA384',
        'ECDHE-RSA-AES256-SHA384',
        'ECDHE-RSA-AES128-GCM-SHA256',
        'ECDHE-RSA-AES128-SHA256',
        'ECDHE-RSA-AES256-SHA',
        'ECDHE-RSA-AES128-SHA',
        'ECDH-ECDSA-AES256-GCM-SHA384',
        'ECDH-ECDSA-AES256-SHA384',
        'ECDH-ECDSA-AES128-GCM-SHA256',
        'ECDH-ECDSA-AES128-SHA256',
        'DHE-RSA-AES256-GCM-SHA384',
        'DHE-RSA-AES256-SHA256',
        'DHE-DSS-AES256-GCM-SHA384',
        'DHE-DSS-AES256-SHA256',
        'DHE-RSA-AES256-SHA',
        'DHE-DSS-AES256-SHA',
        'DHE-DSS-AES128-GCM-SHA256',
        'DHE-RSA-AES128-GCM-SHA256',
        'DHE-RSA-AES128-SHA256',
        'DHE-DSS-AES128-SHA256',
        'DHE-RSA-AES128-SHA',
        'DHE-DSS-AES128-SHA',
        'AES128-GCM-SHA256',
        'AES128-SHA',
        'DES-CBC3-SHA'
      ],
      secure_renegotiate: true,
      reuse_sessions: true,
      honor_cipher_order: true,
      client_renegotiation: false,
      max_connections: :infinity,
      eccs: [		
        :sect571r1, :sect571k1, :secp521r1, :brainpoolP512r1, :sect409k1,		
        :sect409r1, :brainpoolP384r1, :secp384r1, :sect283k1, :sect283r1,		
        :brainpoolP256r1, :secp256k1, :secp256r1, :sect239k1, :sect233k1,		
        :sect233r1, :secp224k1, :secp224r1		
      ]
    ]

    :ranch.child_spec(MyApp.Endpoint.HTTPS, 100, :ranch_proxy_ssl, trans_opts, :cowboy_protocol, proto_opts)

If I keep the eccs key the application fails with the following message:

    ** (EXIT) shutdown: failed to start child: Phoenix.Endpoint.Handler
        ** (EXIT) shutdown: failed to start child: {:ranch_listener_sup, ScalpelWeb.Endpoint.HTTPS}
            ** (EXIT) shutdown: failed to start child: :ranch_acceptors_sup
                ** (EXIT) :badarg

If I remove the `eccs` key :ranch_proxy_ssl works as expected. 

I'm unsure why this is perceived as a bad argument, since you can specify which eccs to use with :ranch_ssl. 

Let me know if you need any additional information to debug.

**Comment by ferd** [comment]
There would be a need to patch `ranch_proxy_ssl` to perceives `eccs` as an SSL option: https://github.com/heroku/ranch_proxy_protocol/blob/master/src/ranch_proxy_ssl.erl#L272-L273
