### ISSUE TITLE
Support Ranch 1.3 and 1.4

### ISSUE THREAD

**Issue by tomciopp** [heroku/ranch_proxy_protocol#34]
I'm using this in a Phoenix project, and I have to use an older release since the project hard codes the ranch version at 1.4.0. Anyone still using v1 of Cowboy is stuck using ranch version 1.3.2. I tried reading the documentation on rebar so that I could fix this myself but there seems to be nothing documenting how to actually declare relaxed versions of dependencies.

My expectation would be to declare the following:

    {deps,
     [
      {ranch, "~> 1.3"}]}.

Given that there doesn't seem to be any API changes related to the upgrade in deps, I think still supporting ranch 1.3 is reasonable.

**Comment by ferd** [comment]
Rebar3 does not have relaxed dependencies, and instead relies on dependency depth to pick which version to keep.

**Comment by tomciopp** [comment]
Forgive me if I'm a bit thick but this is my first interaction with how rebar3 works, and it looks like you are quite heavily involved with the project.

So If I wanted to allow support for ranch 1.4 and 1.3.2 at the same time would I need to change the config file to the following:

    {deps,
     [
      {ranch, "1.4.0"},
      {ranch, "1.3.2"}]}.

If so I will open up a PR here and in the Rebar3 documentation as it is not clear IMO how to solve this problem.

**Comment by ferd** [comment]
No you cannot support multiple libraries at a time. The root of the project picks one and goes with it and that's it. You can be compatible with many, but whatever you pick in a library acts as a 'preferred' version and has no guarantee of running with it later if a project importing both libraries pins another version.

**Comment by tomciopp** [comment]
I saw the star syntax here which I thought could solve the problem. https://github.com/erlang/rebar3/blob/master/rebar.config.sample#L74

    {deps, 
      [
        {ranch, "1.*"}]}.

Realistically shouldn't the version of cowboy (or whatever other webserver) be pinning the version of ranch instead of this module? Or is there just absolutely no way to solve the issue

**Comment by ferd** [comment]
The syntax you see is for old-style git dependencies and ran a regex on the version. It does not apply to packages. Rebar3 does *not* do semantic versioning. Additional information can be had at http://www.rebar3.org/docs/dependencies

In short: whatever the root app specifies goes. If multiple deps specify the same transitive dep, the one closest to the root wins. That is literally it.

**Comment by tomciopp** [comment]
Gotcha. I believe I can resolve this issue by passing the override option in my `mix.exs` file. Either way thank you for educating me a bit on how rebar works 💯
