### ISSUE TITLE
please update hex.pm to support OTP 21

### ISSUE THREAD

**Issue by marcelloceschia** [heroku/ranch_proxy_protocol#43]
it is necessary to update amq_client and support OTP 21 as well

**Comment by fenollp** [comment]
Hi there please cut a minor release for us OTP21 people out there!
More detail on the issue: https://github.com/rabbitmq/rabbitmq-common/issues/269

Thanks & have a nice day

**Comment by ypaq** [comment]
We need to solve this first https://github.com/heroku/ranch_proxy_protocol/pull/41. Feel free to work on the PR.

**Comment by marcelloceschia** [comment]
@ypaq I've updated the `.travis.yml` file to update rebar3 before starting the test

**Comment by ypaq** [comment]
done

**Comment by fenollp** [comment]
Wow you guys published 2.0.0 when 1.6.0 would have sufficed (and be semver).
See diff: https://github.com/heroku/ranch_proxy_protocol/compare/1.5.0...2.0.0

But sure whatever. Thanks!

**Comment by ypaq** [comment]
https://github.com/heroku/ranch_proxy_protocol/pull/39/files#diff-46535931f20110b373c2ce4b45b6035dR90 is a backwards compatibility breaking change.
