### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [heroku/ranch_proxy_protocol#53]
Is this still an ongoing (i.e. maintained) project? I recently opened two PRs for which I've had no feedback.

Thanks.

**Comment by ConnorRigby** [comment]
Also interested in this. This package is now at least one breaking change behind upstream `ranch` causing many incompatibilities with packages.

**Comment by michaelklishin** [comment]
Recent versions of Ranch support Proxy protocol in the core.

**Comment by paulo-ferraz-oliveira** [comment]
@michaelklishin: sure, but there are projects that depend on this and while a minor bump might take a few minutes a cowboy bump and then code adaptation might take much longer. :)
